@@include('../head/head.html.tpl')
@@include('../header/header.html.tpl')
@@include('../content/featured-article.html.tpl')
@@include('../content/latest-articles.html.tpl')
@@include('../footer/footer.html.tpl')